// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTBp1M4UAmuEuhXXzn9t04zBcYB3rbHM',
    appId: '1:654516726159:web:843c18cabc043d600983fa',
    messagingSenderId: '654516726159',
    projectId: 'exam-practice-4377e',
    authDomain: 'exam-practice-4377e.firebaseapp.com',
    storageBucket: 'exam-practice-4377e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWwaIi3L_TrboEXz9GMb0CINwexwd-b-E',
    appId: '1:654516726159:android:28bd04de282e2b220983fa',
    messagingSenderId: '654516726159',
    projectId: 'exam-practice-4377e',
    storageBucket: 'exam-practice-4377e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV0udT2GdWU_mxBatoQx4m4Uk7G7x-Znw',
    appId: '1:654516726159:ios:48589ac69e0bc8520983fa',
    messagingSenderId: '654516726159',
    projectId: 'exam-practice-4377e',
    storageBucket: 'exam-practice-4377e.firebasestorage.app',
    iosBundleId: 'com.example.examPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV0udT2GdWU_mxBatoQx4m4Uk7G7x-Znw',
    appId: '1:654516726159:ios:48589ac69e0bc8520983fa',
    messagingSenderId: '654516726159',
    projectId: 'exam-practice-4377e',
    storageBucket: 'exam-practice-4377e.firebasestorage.app',
    iosBundleId: 'com.example.examPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLTBp1M4UAmuEuhXXzn9t04zBcYB3rbHM',
    appId: '1:654516726159:web:23ff15470fe5edc30983fa',
    messagingSenderId: '654516726159',
    projectId: 'exam-practice-4377e',
    authDomain: 'exam-practice-4377e.firebaseapp.com',
    storageBucket: 'exam-practice-4377e.firebasestorage.app',
  );
}
